{
  "parserOptions": {
    "ecmaVersion": 12,
    "sourceType": "module",
    "ecmaFeatures": {
      "jsx": true
    }
  },
  "rules": {
    "semi": ["warn", "always"],
    "no-extra-semi": "error",
    "brace-style": "error",
    "curly": "error",
    "eqeqeq": "off",
    "block-spacing": "error",
    "camelcase": "error",
    "new-cap": "error",
    "no-const-assign": "error",
    "no-dupe-args": "error",
    "no-dupe-class-members": "error",
    "no-dupe-keys": "error",
    "no-duplicate-imports": "error",
    "no-empty-character-class": "error",
    "no-empty": "off",
    "no-eval": "error",
    "no-ex-assign": "error",
    "no-extend-native": "error",
    "no-extra-boolean-cast": "error",
    "no-extra-parens": ["warn", "functions"],
    "no-fallthrough": "error",
    "no-floating-decimal": "error",
    "no-implied-eval": "error",
    "no-inner-declarations": "error",
    "no-lone-blocks": "error",
    "no-mixed-spaces-and-tabs": "error",
    "no-multi-spaces": "error",
    "no-new-func": "error",
    "no-new-object": "error",
    "no-new-require": "error",
    "no-new-symbol": "error",
    "no-new-wrappers": "error",
    "no-redeclare": "error",
    "no-self-assign": "error",
    "no-self-compare": "error",
    "no-sequences": "error",
    "no-shadow-restricted-names": "error",
    "no-sparse-arrays": "error",
    "no-template-curly-in-string": "error",
    "no-this-before-super": "error",
    "no-throw-literal": "error",
    "no-undef-init": "error",
    "no-unsafe-finally": "error",
    "no-useless-constructor": "error",
    "no-useless-rename": "error",
    "no-unexpected-multiline": "error",
    "no-whitespace-before-property": "error",
    "space-before-blocks": "warn",
    "new-parens": "error",
    "space-in-parens": "error",
    "space-unary-ops": "error",
    "keyword-spacing": "warn",
    "template-curly-spacing": "warn",
    "use-isnan": "warn",
    "constructor-super": "error",
    "no-array-constructor": "error",
    "quotes": ["error", "single"],
    "comma-style": ["error", "last"],
    "comma-dangle": [
      "warn",
      {
        "arrays": "never",
        "objects": "never",
        "imports": "never",
        "exports": "never",
        "functions": "never"
      }
    ],
    "space-before-function-paren": [
      "off",
      {
        "anonymous": "always",
        "named": "always",
        "asyncArrow": "always"
      }
    ],
    "func-call-spacing": ["error", "never"],
    "key-spacing": ["error", { "beforeColon": false }],
    "one-var": ["off"],
    "operator-linebreak": "off",
    "space-infix-ops": ["error"],
    "comma-spacing": ["error", { "before": false, "after": true }],
    "no-unused-vars": ["warn", { "vars": "local", "args": "none", "ignoreRestSiblings": false }]
  }
}
